name: only-Aaron-lv-jd_scripts
on:
  schedule:
    - cron: '1 0-23/4 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: only-Aaron-lv-jd_scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: only-Aaron-lv-jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Aaron-lv/sync.git"
          source_branch: "jd_scripts"
          destination_branch: "jd_scripts"
          github_token: ${{ secrets.PAT }}
